# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-03 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('email', models.TextField(null=True)),
                ('tel', models.CharField(max_length=10, null=True)),
                ('played', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('victoire', models.IntegerField(default=0)),
                ('nul', models.IntegerField(default=0)),
                ('defaite', models.IntegerField(default=0)),
                ('buts', models.IntegerField(default=0)),
                ('classement', models.IntegerField(null=True)),
                ('classement_last', models.IntegerField(null=True)),
                ('titulaire', models.BooleanField(default=False)),
                ('paiement', models.BooleanField(default=False)),
                ('photo', models.TextField(null=True)),
            ],
        ),
    ]
