# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-03 17:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fcc', '0003_match_datematch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fcc.Session'),
        ),
    ]
