# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-03 19:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fcc', '0004_auto_20160403_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resultats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipe', models.CharField(default='A', max_length=1)),
                ('buts', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('victoire', models.IntegerField(default=0)),
                ('nul', models.IntegerField(default=0)),
                ('defaite', models.IntegerField(default=0)),
                ('buts', models.IntegerField(default=0)),
                ('classement', models.IntegerField(null=True)),
                ('classement_last', models.IntegerField(null=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fcc.Session')),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='buts',
            new_name='inscrit',
        ),
        migrations.RemoveField(
            model_name='user',
            name='classement',
        ),
        migrations.RemoveField(
            model_name='user',
            name='classement_last',
        ),
        migrations.RemoveField(
            model_name='user',
            name='defaite',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nul',
        ),
        migrations.RemoveField(
            model_name='user',
            name='played',
        ),
        migrations.RemoveField(
            model_name='user',
            name='points',
        ),
        migrations.RemoveField(
            model_name='user',
            name='victoire',
        ),
        migrations.AddField(
            model_name='match',
            name='scoreA',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='scoreB',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stats',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fcc.User'),
        ),
        migrations.AddField(
            model_name='resultats',
            name='match',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fcc.Match'),
        ),
        migrations.AddField(
            model_name='resultats',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fcc.User'),
        ),
    ]
