# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-03 19:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fcc', '0005_auto_20160403_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipe', models.CharField(default='A', max_length=1)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fcc.Session')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fcc.User')),
            ],
        ),
    ]
