# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 09:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fcc', '0009_auto_20160407_2158'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFCC',
            fields=[
                ('iduserFCC', models.AutoField(primary_key=True, serialize=False)),
                ('tel', models.CharField(blank=True, max_length=10, null=True)),
                ('titulaire', models.BooleanField(default=False)),
                ('inscrit', models.IntegerField(default=0)),
                ('paiement', models.BooleanField(default=False)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='/avatar/')),
            ],
        ),
        migrations.RenameModel(
            old_name='Resultats',
            new_name='Resultat',
        ),
        migrations.RenameModel(
            old_name='Stats',
            new_name='Stat',
        ),
        migrations.RemoveField(
            model_name='compo',
            name='user',
        ),
        migrations.RemoveField(
            model_name='resultat',
            name='user',
        ),
        migrations.RemoveField(
            model_name='stat',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='userfcc',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compo',
            name='userFCC',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fcc.UserFCC'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resultat',
            name='userFCC',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fcc.UserFCC'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stat',
            name='userFCC',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fcc.UserFCC'),
            preserve_default=False,
        ),
    ]
