# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-20 05:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fcc', '0012_auto_20160409_1934'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id_award', models.AutoField(primary_key=True, serialize=False)),
                ('annee', models.IntegerField(default='2015')),
                ('nom_award', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AwardVainqueur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fcc.Award')),
                ('userFCC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fcc.UserFCC')),
            ],
        ),
    ]
