# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-22 10:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fcc', '0014_auto_20160521_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('userFCC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fcc.UserFCC')),
            ],
        ),
    ]
