# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-26 19:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fcc', '0017_auto_20160525_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteMatch',
            fields=[
                ('id_note', models.AutoField(primary_key=True, serialize=False)),
                ('note', models.IntegerField(default='0')),
                ('joueur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Joueur', to='fcc.UserFCC')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fcc.Match')),
                ('userFCC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Votant', to='fcc.UserFCC')),
            ],
        ),
    ]
