# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-29 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcc', '0021_auto_20160529_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultat',
            name='moyenne_note',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=3, null=True),
        ),
    ]
